import streamlit as st
import pandas as pd
from datetime import datetime, timedelta

# --- 頁面配置 ---
st.set_page_config(page_title="Global Intelligence Pulse 2026", layout="wide")

# --- 模擬數據抓取邏輯 (實際應對接 API 或 Scraper) ---
def fetch_data(layer, timeframe_hours):
    # 這裡未來應整合 NewsAPI, Twitter API, Reddit API 等
    # 目前以 Placeholder 模擬資料結構
    return [
        {
            "title_tw": f"【層次{layer}】最新國際情勢分析 - {i+1}",
            "title_en": f"[Layer {layer}] Global Situation Analysis - {i+1}",
            "category": "川普政府政策",
            "content": "這裡將會由 Gemini 生成 200~500 字的深度分析內容，涵蓋金融、科技、能源等維度...",
            "url": "https://example.com/news",
            "timestamp": (datetime.now() - timedelta(hours=i)).strftime("%Y-%m-%d %H:%M")
        } for i in range(10)
    ]

# --- Sidebar 導覽與控制 ---
st.sidebar.title("🌐 全球情報監控系統")
st.sidebar.info("使用者：Ethan | 權限：頂級決策支援")

selected_layer = st.sidebar.radio(
    "選擇情報層次",
    ["層次一：已發生 (權威新聞)", "層次二：正在發生 (社群脈動)", "層次三：將要發生 (預警分析)"]
)

update_freq = st.sidebar.selectbox(
    "更新時間區段",
    options=[1, 4, 8, 24],
    format_func=lambda x: f"最近 {x} 小時"
)

if st.sidebar.button("🔄 立即搜尋並更新"):
    st.cache_data.clear()
    st.toast("正在抓取最新全球數據...", icon="🚀")

# --- 主介面設計 ---
st.title(f"📊 {selected_layer}")
st.caption(f"數據最後更新時間: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

# 分類篩選標籤
tabs = st.tabs(["全部內容", "川普政策", "金融/通膨", "資訊科技", "油價能源", "戰局風向"])

# 模擬獲取資料
layer_code = selected_layer[2] # 取得 1, 2 或 3
data = fetch_data(layer_code, update_freq)

with tabs[0]:
    for idx, item in enumerate(data):
        with st.expander(f"📌 {item['title_tw']} | {item['title_en']}", expanded=(idx==0)):
            col1, col2 = st.columns([1, 1])
            
            with col1:
                st.subheader("🇹🇼 中文摘要")
                st.markdown(f"**類別：** `{item['category']}`")
                st.write(f"（此處將呈現 200-500 字的中文化深度分析，包含對半導體、AI、以及烏克蘭/中東戰局的影響評估...）")
                st.write(item['content'])
                
            with col2:
                st.subheader("🇺🇸 English Summary")
                st.markdown(f"**Category:** `{item['category']}`")
                st.write(f"(Detailed analysis of 200-500 words generated by Gemini, focusing on Trump administration policies, financial impacts, and tech trends...)")
            
            st.divider()
            st.markdown(f"🔗 [點擊查看原文來源]({item['url']}) | ⏰ 發佈時間：{item['timestamp']}")

# --- 底部統計圖表 (以金融/能源為例) ---
st.sidebar.divider()
st.sidebar.subheader("📈 關鍵指標監控")
st.sidebar.metric("布蘭特原油 (Brent)", "$84.50", "+2.5%")
st.sidebar.metric("美元指數 (DXY)", "104.2", "-0.15%")
st.sidebar.metric("NVDA (模擬 2026)", "$1,850", "+1.2%")
